name: obs
sha1: f132348a6257cb2bf54fcd3b47764aa7185c8ce0
options:
  basename: obs
  elf_path: obs.bin
  target_path: rom/overlay/obs.bin
  find_file_boundaries: False
  asm_path: asm
  symbol_addrs_path:
   - overlay/obs_symbol_addrs.txt
   - symbol_addrs.txt
   - sdk_symbol_addrs.txt
  reloc_addrs_path: obs_reloc_addrs.txt
  ld_script_path: linkers/obs.ld
  undefined_funcs_auto_path: linkers/obs_undefined_funcs_auto.main.txt
  undefined_syms_auto_path: linkers/obs_undefined_syms_auto.main.txt
  symbol_name_format: $VRAM_$SEG
segments:
  - name: obs
    type: code
    vram: 0x1F01E00
    start: 0x0
    bss_size: 0x80
    subsegments:
      - [0x0, databin, obs_overlay_header]
      - [0x80, asm, Event/stage/stg_ovservation]
      - [0xD00, data, Event/stage/stg_ovservation_data]
      - { vram: 0x1F02E80, type: bss, name: Event/stage/stg_ovservation_bss }
  - [0x1080]
