name: Silent Hill 3 (USA)
sha1: dbb94538294b21be38035c0ce6b78354bdfdf2a7
options:
  basename: SLUS_206.22
  target_path: rom/SLUS_206.22
  elf_path: SLUS_206.22
  find_file_boundaries: True
  asm_path: asm
  rodata_string_guesser_level: 0
  symbol_addrs_path: 
    - symbol_addrs.txt
    - shim_addrs.txt
  reloc_addrs_path:
    - reloc_addrs.txt
    - shim_reloc_addrs.txt
  gp_value: 0x3d09f0
  ld_script_path: linkers/SLUS_206.22.ld
  undefined_funcs_auto_path: linkers/sh3_undefined_funcs_auto.main.txt
  undefined_syms_auto_path: linkers/sh3_undefined_syms_auto.main.txt
  asm_nonmatching_label_macro: ""
  migrate_rodata_to_functions: True
  pair_rodata_to_text: True
  section_order: [".text", ".vutext", ".data", ".rodata", ".lit4", ".sdata", ".bss"]
  symbol_name_format: $VRAM
segments:
  - [0x0]
  - name: engine
    type: code
    start: 0x580
    vram: 0x00100000
    bss_size: 0x1BA4B00
    subsegments:
      - [0x000580, asm,     crt0]
      - [0x000760, asm,     text_0x000760]
      - { start: 0x0022c8, type: asm, name: sce,  ld_align_segment_start: 0x8  }
      - [0x0220b0, asm,     sdk/libdbc]
      - [0x022b10, asm,     sdk/libgcc]
      - [0x02bfe8, asm,     unk]
      - { start: 0x02cff0, type: c,   name: main, ld_align_segment_start: 0x10 }
      - [0x02d2a0, asm,     text_0x02d2a0]
      - [0x02f3e0, c,       Chacter/m3_sc]
      - [0x030140, asm,     text_0x030140]
      - [0x039210, asm,     Fog/spack]
      - [0x03a840, asm,     text_0x03a840]
      - [0x03baa0, c,       DS_Pad/ds_sequencer]
      - [0x03d290, asm,     text_0x03d290]
      - [0x040950, c,       Chacter_Draw/clani]
      - [0x0410c0, asm,     text_0x0410c0]
      - [0x041640, c,       Effect2/hh_class_manager]
      - [0x042750, asm,     text_0x042750]
      - [0x042a80, c,       Effect2/hh_class_wrapper]
      - [0x043460, c,       Chacter/m3_bgobj]
      - [0x043680, asm,     text_0x043680]
      - [0x053920, c,       fsserve]
      - [0x055790, asm,     text_0x055790]
      - [0x057150, c,       Font/dic]
      - [0x0582b0, c,       Font/font]
      - [0x05e0f0, asm,     text_0x05e0f0]
      - [0x06fc20, asm,     Event/picture]
      - [0x070990, asm,     text_0x070990]
      - [0x077880, c,       sh3shd/sh3shd_shadow_vu1_packet]
      - [0x0782b0, asm,     text_0x0782b0]
      - [0x086930, c,       sh3shd/sh3shd_shadow_model]
      - [0x08ac50, asm,     text_0x08ac50]
      - [0x0905d0, c,       Chacter/m3_play_event]
      - [0x090e00, asm,     text_0x090e00]
      - [0x09afb0, c,       SH3_common/sh_vu0]
      - [0x09b9d0, asm,     text_0x09b9d0]
      - [0x09ec40, c,       Collision/cl_calc]
      - [0x09ec80, asm,     text_0x09ec80]
      - [0x09fcd0, c,       Collision/cl_main]
      - [0x0a7e20, asm,     text_0x0a7e20]
      - [0x0aa0e0, c,       GFW/sh3gfw_viewclip]
      - [0x0ab250, asm,     text_0x0ab250]
      - [0x0b55b0, c,       GFW/sh3gfw_Texpacket]
      - [0x0b6890, asm,     text_0x0b6890]
      - [0x0b71a0, asm,     view/vc_calc]
      - [0x0b7750, asm,     view/vc_main]
      - [0x0bf480, asm,     text_0x0bf480]
      - [0x0c2130, c,       Heap/utilheap]
      - [0x0c2360, asm,     text_0x0c2360]
      - [0x0d33f0, c,       Chacter_Draw/model3_n]
      - [0x0d3d00, c,       Chacter_Draw/model3_sub_n]
      - [0x0d42d0, c,       Chacter_Draw/model3_vu0_n]
      - [0x0d6df0, c,       Chacter_Draw/model3_vu1_n]
      - [0x0d90b0, asm,     text_0x0d90b0]
      - [0x0dc100, c,       DBG/dbfntprint]
      - [0x0dc410, asm,     text_0x0dc410]
      - [0x0dc4d0, asm,     sdk/kernel]
      - [0x0dc970, asm,     text_0x0dc970]
      - [0x0e70a0, c,       Fog/fog]
      - [0x0eb070, asm,     text_0x0eb070]
      - [0x0eb610, c,       Fog/fogdata]
      - [0x0eca00, asm,     text_0x1ec480]
      - [0x0ef080, c,       Effect2/hh_class_cartridge]
      - [0x0f0920, asm,     text_0x0f0920]
      - [0x0fdfa0, asm,     cri/cri_0] 
      - [0x10eff0, asm,     text_0x10eff0]
      - [0x10f050, c,       Multi_thr/scf/ps2_scf]
      - [0x10f350, asm,     text_0x10f350]
      - [0x110b40, c,       Effect2/hh_class_blood_01]
      - [0x111420, asm,     Effect2/hh_class_1]
      - [0x111c10, asm,     Effect2/hh_class_2]
      - [0x112100, asm,     Effect2/hh_class_3]
      - [0x1128f0, asm,     Effect2/hh_class_4]
      - [0x1133a0, asm,     Effect2/hh_class_5]
      - [0x113cc0, asm,     text_0x113cc0]
      - [0x116520, asm,     Enemy/en_one]        # DOUBLE_HEAD
      - [0x117770, asm,     text_0x117770]
      - [0x1261a0, asm,     Enemy/en_smb]        # SPLIT_WORM
      - [0x12ef30, asm,     text_0x12ef30]
      - [0x12f0f0, c,       Enemy/en_common]
      - [0x130590, asm,     Enemy/en_aid]        # CLOSER
      - [0x1319c0, asm,     text_0x1319c0]
      - [0x141890, asm,     Chacter/m3_claudia]  # CLAUDIA
      - [0x141b20, asm,     Effect2/hh_class_6]
      - [0x142490, asm,     Effect2/hh_class_7]
      - [0x142d90, asm,     Effect2/hh_class_8]
      - [0x143870, asm,     text_0x143870]
      - [0x143a40, asm,     Enemy/en_ckn]        # NUMB_BODY
      - [0x144620, asm,     text_0x144620]
      - [0x15dcd0, asm,     Enemy/en_nse]        # NURSE
      - [0x15e760, asm,     text_0x15e760]
      - [0x166ad0, asm,     Enemy/en_deb]        # INSANE_CANCER
      - [0x170a20, asm,     text_0x170a20]
      - [0x187340, asm,     Enemy/en_apb]        # MISSIONARY
      - [0x1876c0, asm,     text_0x1876c0]
      - [0x191480, asm,     Enemy/en_fly]        # PENDULUM
      - [0x19b1f0, asm,     text_0x19b1f0]
      - [0x1a9e40, asm,     Item/item_menu_select]
      - [0x1b2ba0, asm,     text_0x1b2ba0]
      - [0x1b41d0, asm,     movie/pss_audiodec]
      - [0x1b4a70, asm,     movie/pss_cscvu1]
      - [0x1b5ae0, asm,     movie/pss_disp]
      - [0x1b6b30, asm,     movie/pss_main]
      - [0x1b7ad0, asm,     movie/pss_read]
      - [0x1b7cf0, asm,     movie/pss_readbuf]
      - [0x1b7e90, asm,     movie/pss_strfile]
      - [0x1b7fb0, c,       movie/pss_vibuf]
      - [0x1b8f50, c,       movie/pss_videodec]
      - [0x1b99a0, c,       movie/pss_vobuf]
      - [0x1b9c20, asm,     text_0x1b9c20]
      - [0x1ba6a0, asm,     Enemy/en_ap2]        # SCRAPER
      - [0x1c2760, asm,     text_0x1c2760]
      - [0x1d2630, asm,     Enemy/en_shb]        # GOD
      - [0x1d75a0, asm,     Enemy/en_rod]        # SEWER_MONSTER
      - [0x1d7610, asm,     text_0x1d7610]
      - [0x1e01c0, asm,     Enemy/en_mry]        # CAROUSEL_HORSE
      - [0x1e0360, asm,     text_0x1e0360]
      - [0x1e0c80, asm,     Enemy/en_bhr]        # MEMORY_OF_ALESSA
      - [0x1e1490, asm,     text_0x1e1490]
      - [0x1eea70, asm,     Enemy/en_ded1]       # EN_DED1
      - [0x1eea80, asm,     text_0x1eea80]
      - [0x1f3330, asm,     Effect2/hh_class_9]
      - [0x1f3d50, asm,     Effect2/hh_class_A]
      - [0x1f4a10, asm,     text_0x1f4a10]
      - [0x1fe600, asm,     Chacter/m3_valtiel]
      - [0x1fe760, asm,     text_0x1fe760]
      - [0x2048e0, asm,     Enemy/en_lie]        # SLURPER_E
      - [0x205860, asm,     text_0x205860]
      - [0x20e0d0, c,       Enemy/en_lix]        # SLURPER_X
      - [0x210790, asm,     text_0x210790]
      - [0x2207b0, asm,     MC/mc]
      - [0x225cb0, asm,     text_0x225cb0]
      - [0x230440, asm,     Effect2/hh_class_new]
      - [0x230b00, asm,     text_0x230b00]
      - [0x2345b0, c,       Effect2/hh_class_0x2345b0]
      - [0x234ee0, asm,     text_0x234ee0]
      - [0x238080, textbin, vutext]
      - [0x23aa80, data,    data]
      - [0x24f4c0, rodata,  rodata_0x24f4c0]
      - [0x257420, .rodata, Chacter_Draw/clani]
      - [0x257478, rodata,  rodata_0x257478]
      - [0x266e90, .rodata, Chacter_Draw/model3_sub_n]
      - [0x266f60, rodata,  rodata_0x266f60]
      - [0x29e180, .rodata, movie/pss_vibuf]
      - [0x29e198, .rodata, movie/pss_videodec]
      - [0x29e1d0, rodata,  rodata_0x29e1d0]
      - [0x2be000, .rodata, DS_Pad/ds_sequencer]
      - [0x2be020, rodata,  rodata_0x2be020]
      - [0x2be940, .rodata, Font/font]
      - [0x2be970, rodata,  rodata_0x2be970]
      - [0x2bf310, .rodata, Chacter/m3_play_event]
      - [0x2bf420, rodata,  rodata_0x2bf420]
      - [0x2bf8d0, .rodata, Collision/cl_main]
      - [0x2bf910, rodata,  rodata_0x2bf910]
      - [0x2c0260, .rodata, Fog/fog]
      - [0x2C02B0, rodata,  rodata_0x2c02b0]
      - [0x2C4478, .rodata, Multi_thr/scf/ps2_scf]
      - [0x2C4480, rodata,  rodata_0x2c4480]
      - [0x2c5080, .rodata, Enemy/en_common]
      - [0x2c5110, rodata,  rodata_0x2c5110]
      - [0x2c8790, .rodata, Enemy/en_lix]
      - [0x2c8910, rodata,  rodata_0x2c8910]
      - [0x2c8f80, lit4,    lit4]
      - [0x2c8fb0, sdata,   sdata]
      - { vram: 0x03c8b00,  type: bss,  name: bss_0x03c8b00 }
      - { vram: 0x046d270,  type: .bss, name: Chacter_Draw/clani }
      - { vram: 0x046e870,  type: bss,  name: bss_0x046e870}
      - { vram: 0x1d0efb0,  type: .bss, name: Font/font }
      - { vram: 0x1d30570,  type: bss,  name: bss_0x1d30570 }
  - [0x2C9080]
